import { Button, Col, Input, Row } from 'antd';
import type { NextPage } from 'next';
import Head from 'next/head';

const Recruiter: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hifi</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Row justify='center'>
        <Col>Hello, this page is for recruiters</Col>
        <Col>
          <Button className='w-100' type='primary'>
            Click here
          </Button>
        </Col>
      </Row>
    </>
  );
};

export default Recruiter;
