import 'antd/dist/antd.css';
import type { AppProps } from 'next/app';
// import 'react-quill/dist/quill.snow.css';
import { Provider } from 'react-redux';
import Head from 'next/head';
import Header from 'components/layouts/Header';
import Footer from 'components/layouts/Footer';
import { store } from 'redux/store';
import 'tailwindcss/tailwind.css';
import menu from 'constant/menu';
require('../styles/App.less');
require('../styles/global.less');

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <Head>
        <title>Hifi</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex flex-col h-screen'>
        <Header menu={menu}></Header>
        <main className='flex-1 bg-[#EBEFF7]'>
          <Component {...pageProps} />
        </main>
        <Footer></Footer>
      </div>
    </Provider>
  );
}

export default MyApp;
