import 'antd/dist/antd.css';
import type { AppProps } from 'next/app';
// import 'react-quill/dist/quill.snow.css';
import { Provider } from 'react-redux';
import Head from 'next/head';
import Header from 'components/layouts/Header';
import Footer from 'components/layouts/Footer';
import { HomeOutlined } from '@ant-design/icons';
import { store } from 'redux/store';
import 'tailwindcss/tailwind.css';
require('../styles/App.less');
require('../styles/global.less');

function MyApp({ Component, pageProps }: AppProps) {
  const menu = [
    {
      id: 1,
      name: 'Jobs',
      url: './jobs',
      icon: <HomeOutlined />,
    },
    {
      id: 2,
      name: 'Companies',
      url: './companies',
      icon: <HomeOutlined />,
    },
  ];
  return (
    <Provider store={store}>
      <Head>
        <title>Hifi</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header menu={menu}></Header>
      <Component {...pageProps} />
      <Footer></Footer>
    </Provider>
  );
}

export default MyApp;
